// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEndASP.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    partial class SystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEndASP.Entities.PropertyStudentLikes", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.ToTable("StudentPropertiesLikes");

                    b.HasData(
                        new
                        {
                            StudentId = "db4b200c-3a2d-4d36-b6df-84a40a5e974d",
                            PropertyId = 2
                        },
                        new
                        {
                            StudentId = "5f3c109a-2029-4301-bd7c-4a5a5d97de8e",
                            PropertyId = 2
                        });
                });

            modelBuilder.Entity("BackEndASP.Entities.UserConnection", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OtherStudentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentId", "OtherStudentId");

                    b.HasIndex("OtherStudentId");

                    b.ToTable("UserConnections");
                });

            modelBuilder.Entity("Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeComplement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Long")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Building");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("ImageData64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "2fe5b0ff-9f85-4b59-a2fc-a45a710b8709",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "df2921d9-f398-435d-953b-723acdd41fff",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5f3c109a-2029-4301-bd7c-4a5a5d97de8e",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "db4b200c-3a2d-4d36-b6df-84a40a5e974d",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Moment")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserIdWhoSendNotification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique()
                        .HasFilter("[ImageId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = "2fe5b0ff-9f85-4b59-a2fc-a45a710b8709",
                            AccessFailedCount = 0,
                            BirthDate = new DateTimeOffset(new DateTime(2024, 5, 3, 13, 22, 22, 785, DateTimeKind.Unspecified).AddTicks(9427), new TimeSpan(0, -3, 0, 0, 0)),
                            ConcurrencyStamp = "2c60299f-2f53-4282-8dba-8b7545c712de",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 5, 3, 16, 22, 22, 677, DateTimeKind.Unspecified).AddTicks(4625), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAED6gumXRH4kKUidMWBOsbLFNPMRNTInsMlWjWyhoY0LL67mb/H3FpqXr6IY8utdNdQ==",
                            PhoneNumber = "999999999",
                            PhoneNumberConfirmed = true,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "c01cf85b-84ab-4f22-819d-70554231300c",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("College", b =>
                {
                    b.HasBaseType("Building");

                    b.HasDiscriminator().HasValue("College");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rodovia Senador José Ermírio de Moraes",
                            District = "Sorocaba",
                            HomeComplement = "",
                            Lat = "-23.469645838524144",
                            Long = "-47.42976187034831",
                            Name = "FACENS",
                            Neighborhood = "Iporanga",
                            Number = "",
                            State = "SP"
                        });
                });

            modelBuilder.Entity("Property", b =>
                {
                    b.HasBaseType("Building");

                    b.Property<string>("Bathrooms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bedrooms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("Property");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Address = "Rua Achiles Audi",
                            District = "Cerquilho",
                            HomeComplement = "Casa",
                            Lat = "-23.1723808873683",
                            Long = "-47.74702041600901",
                            Name = "Casa de aluguel",
                            Neighborhood = "Centro",
                            Number = "1054",
                            State = "SP",
                            Bathrooms = "2",
                            Bedrooms = "3",
                            Description = "Excelente casa, localizada em um excelente lugar, 2 banheiros sendo 1 suite, tres quartos, sala, cozinha e garagem que cabe 3 carros tranquilamente",
                            OwnerId = "df2921d9-f398-435d-953b-723acdd41fff",
                            Price = 1200.0
                        });
                });

            modelBuilder.Entity("BackEndASP.Entities.Owner", b =>
                {
                    b.HasBaseType("User");

                    b.HasDiscriminator().HasValue("Owner");

                    b.HasData(
                        new
                        {
                            Id = "df2921d9-f398-435d-953b-723acdd41fff",
                            AccessFailedCount = 0,
                            BirthDate = new DateTimeOffset(new DateTime(2024, 5, 3, 13, 22, 22, 876, DateTimeKind.Unspecified).AddTicks(6799), new TimeSpan(0, -3, 0, 0, 0)),
                            ConcurrencyStamp = "3e606f37-0ad5-4827-8f49-ca2e1fa855c2",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 5, 3, 16, 22, 22, 786, DateTimeKind.Unspecified).AddTicks(295), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "owner@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Owner",
                            NormalizedEmail = "OWNER@GMAIL.COM",
                            NormalizedUserName = "OWNER",
                            PasswordHash = "AQAAAAIAAYagAAAAEA01rLmEe8+7ZOXghesMejUjmGUmf5960rertwREm8pD9L2Q/ar+7EyzE+xNUBzcyw==",
                            PhoneNumber = "999999999",
                            PhoneNumberConfirmed = true,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "5a369c54-0c1b-4afb-bcbd-1e0dffb96e21",
                            TwoFactorEnabled = false,
                            UserName = "Owner"
                        });
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.HasBaseType("User");

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("Hobbies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdsPersonsIConnect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PendentsConnectionsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personalities")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CollegeId");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = "5f3c109a-2029-4301-bd7c-4a5a5d97de8e",
                            AccessFailedCount = 0,
                            BirthDate = new DateTimeOffset(new DateTime(2024, 5, 3, 13, 22, 22, 984, DateTimeKind.Unspecified).AddTicks(2460), new TimeSpan(0, -3, 0, 0, 0)),
                            ConcurrencyStamp = "c3b77215-804b-4dee-9a01-29ed2f96a932",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 5, 3, 16, 22, 22, 876, DateTimeKind.Unspecified).AddTicks(7287), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "student@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Student",
                            NormalizedEmail = "STUDENT@GMAIL.COM",
                            NormalizedUserName = "STUDENT",
                            PasswordHash = "AQAAAAIAAYagAAAAEPaixf9JvDWdnN9qyxFCfciWSnK0a2uetU71/xjYHTI322SFYCbHkHfxEfamRNSAeA==",
                            PhoneNumber = "999999999",
                            PhoneNumberConfirmed = true,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "22a2ae67-781f-481d-ac3d-e7fd28d4e970",
                            TwoFactorEnabled = false,
                            UserName = "Student",
                            CollegeId = 1,
                            Hobbies = "[]",
                            IdsPersonsIConnect = "[]",
                            PendentsConnectionsId = "[]",
                            Personalities = "[]"
                        },
                        new
                        {
                            Id = "db4b200c-3a2d-4d36-b6df-84a40a5e974d",
                            AccessFailedCount = 0,
                            BirthDate = new DateTimeOffset(new DateTime(2024, 5, 3, 13, 22, 23, 80, DateTimeKind.Unspecified).AddTicks(8238), new TimeSpan(0, -3, 0, 0, 0)),
                            ConcurrencyStamp = "ffa87a5f-2beb-4dd5-9538-602abc00e9c9",
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 5, 3, 16, 22, 22, 984, DateTimeKind.Unspecified).AddTicks(3564), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "joao@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Joao",
                            NormalizedEmail = "JOAO@GMAIL.COM",
                            NormalizedUserName = "JOAO",
                            PasswordHash = "AQAAAAIAAYagAAAAEMqduVExh8AjbAD8loF1vb5tEDhySm8yjh4hDtoYSYt9DGVjIBLnjR7n7vq15BFu+g==",
                            PhoneNumber = "999999999",
                            PhoneNumberConfirmed = true,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "fa185a54-4aab-43d4-875a-5f9f2e0e09ba",
                            TwoFactorEnabled = false,
                            UserName = "Joao",
                            CollegeId = 1,
                            Hobbies = "[\"League of Legends\",\"Pop\",\"Carros\"]",
                            IdsPersonsIConnect = "[]",
                            PendentsConnectionsId = "[]",
                            Personalities = "[\"Timido\",\"Quieto\",\"Amigavel\"]"
                        });
                });

            modelBuilder.Entity("BackEndASP.Entities.PropertyStudentLikes", b =>
                {
                    b.HasOne("Property", "Property")
                        .WithMany("StudentLikes")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Student", "Student")
                        .WithMany("PropertiesLikes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BackEndASP.Entities.UserConnection", b =>
                {
                    b.HasOne("Student", "OtherStudent")
                        .WithMany()
                        .HasForeignKey("OtherStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Student", "Student")
                        .WithMany("Connections")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OtherStudent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Image", b =>
                {
                    b.HasOne("Building", "Building")
                        .WithMany("Images")
                        .HasForeignKey("BuildingId");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Image", "Image")
                        .WithOne("User")
                        .HasForeignKey("User", "ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Property", b =>
                {
                    b.HasOne("BackEndASP.Entities.Owner", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.HasOne("College", "College")
                        .WithMany("Students")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("College");
                });

            modelBuilder.Entity("Building", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Image", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("College", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Property", b =>
                {
                    b.Navigation("StudentLikes");
                });

            modelBuilder.Entity("BackEndASP.Entities.Owner", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("PropertiesLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
